### ISSUE TITLE
Can you add function Category, and candidatesreviews?

### ISSUE THREAD

**Issue by MIMAXUZ** [Learning-From-Scratch/Job-Portal#4]
I have one idea, If you could, add post, see job by category, and reviews for candidates,

**Comment by BossMan1994** [comment]
This is supposed to be basic implementation of job portal so people can get started with php easily. At the moment I don't have any plans to add more functionality to this. But if you want to contribute and add functionality to this then free feel to do that and push your changes. I will surely add your name to contribution list.
